### ISSUE TITLE
Make it easy to support blogs rooted other than at /

### ISSUE THREAD

**Issue by tfeb** [greghendershott/frog#119]
I have an existing site, and I want to use frog to create a blog hanging below a directory in that site, without perturbing the existing structure  So I want to create a structure like
- `<root>/index.html` -- main index
- `<root>/feeds/...` -- feeds

and so on: I want absolutely everything to hang beneath `<root>`.

It is at best painful to do this at present, and I'm not sure it's completely possible, because things like feed links seem to have hardwired URLS which look like `/feeds/...`.  It may be that this is just a documentation (or comprehension on my part) problem, but I'm not sure.  In any case it would be cool if this was easier to do.

**Comment by greghendershott** [comment]
Thank you for working on this! I wanted to comment and let you know I haven't forgotten about it. I did read through your changes. They seem reasonable and I don't see any obvious problems or omissions. But -- my brain had a cache miss on some of the details of what Frog is doing. :) So, I'll need to find a chunk of time to reload, and to study it more carefully.

**Comment by tfeb** [comment]
That's fine of course.  For what it's worth I've been using it for a while and it empirically works though this doesn't mean it's actually the right answer! I've been rebasing my branch on master and can push that if/when you want to do a pull (I know push/rebase/push is evil but it can make things easier).

Let me know if/when you want me to make a pull request.

**Comment by greghendershott** [comment]
Done with #126 and additional commits.
