### ISSUE TITLE
support for live-reload

### ISSUE THREAD

**Issue by gour** [greghendershott/frog#124]
Hello,

Do you have any plan to add  support for live-reload feature to the Frog which enables one to start server on *localhost* and see instant changes of the rendered site after adding/changing content?

It's very useful and popular feature in my static site generators...

**Comment by greghendershott** [comment]
There's a `-w` / `--watch` flag. For example I use `raco frog -bwp` (short for `raco frog --build --watch --preview`).

Does that do what you mean?

**Comment by greghendershott** [comment]
By the way, this rebuilds the HTML files. However frog doesn't know how to tell your browser to refresh the page (re-read the HTML files). So you'll need to do that manually (unless there's some browser extension for that; but I just refresh manually).

**Comment by gour** [comment]
> There's a -w / --watch flag. For example I use raco frog -bwp (short for raco frog --build --watch --preview).

Ahh, I missed it. :-(

> Does that do what you mean?

Kind of...

> So you'll need to do that manually (unless there's some browser extension for that; but I just refresh manually).

OK, that's the missing part. :-)
