### ISSUE TITLE
Support ~user style uri-prefix

### ISSUE THREAD

**Issue by khinsen** [greghendershott/frog#136]
I am trying to use frog for a small site that lives in my personal space on some Web server. This means that all URLs (links, image references, ...) must be prefixed with `~username`. I haven't found any way to to this, although there is an undocumented configuration parameter `uri-prefix` that looks promising.

**Comment by greghendershott** [comment]
That's interesting timing -- this got added literally within the last 24 hours.

Longer discussion here: issue #126.

---

>  there is an undocumented configuration parameter uri-prefix that looks promising

It is discussed near the end of the README: [Embedding a blog in an existing site](https://github.com/greghendershott/frog#embedding-a-blog-in-an-existing-site).

However I notice that I overlooked updating the [.frogrc section of the README](https://github.com/greghendershott/frog#per-project-configuration-frogrc) with [the new part of the example .frogrc](https://github.com/greghendershott/frog/blob/master/example/.frogrc#L4-L7):

```sh
# A path prepended to URIs, including those specified here in .frogrc
# such as `permalink` and `posts-index-uri`. Defaults to `/`. This is
# useful when you want to embed your blog in another web site.
uri-prefix = /
```

I'll do that now.

---

If the documentation is still unclear or weak, for you, it would be really helpful if you could let me know how. What questions you still have, or how you find it confusing. So I can improve it.

**Comment by khinsen** [comment]
Thanks for the just-in-time implementation!  ;-)

The documentation is now clear about what `uri-prefix` does. What I don't see yet is how I can use it for solving my problem.

For a site living in my personal Web space, I'd need `uri-prefix = /~user/`. Test: do `raco frog --init`, change `uri-prefix` in `.frogrc`, do `raco frog -bp`. Doesn't work. I'd have to put my files into a directory called `~user`, but that's not a valid directory name.

It gets worse when I have links in my pages, for example to images. The link must be `/img/foo.png` for previewing but `/~user/img/foo.png` for deployment. I'd need a way to have Frog prepend `uri-prefix` to links inside my posts and pages. There doesn't seem to be one.

**Comment by greghendershott** [comment]
Aside from the `~` problem, preview should work well. There's a new `--root` flag to tell the preview web server the root. Which you probably won't need to supply; it defaults to as many parent dirs as there are dirs in `uri-preview`, minus one.

But yeah, `~user` won't work as a local file pathname.  I wonder if the fix could be as simple as Frog deleting the `~` when forming a local path pathname. Thinking...

**Comment by khinsen** [comment]
Some form of name-mangling for turning `uri-prefix` into a valid directory name is at the minimum a useful workaround.

**Comment by greghendershott** [comment]
Could you `mkdir \~user`?

**Comment by greghendershott** [comment]
That works for me.

For example in your Frog project root dir:

    $ mkdir \~user

In its `.frogrc`:

    uri-prefix = /~user
    output-dir = ~user

That generates what seem to be correct URIs. `raco frog -p` opens automatically at `http://localhost:3000/~user/index.html` where the page is. Links to posts work.

Re images and CSS etc., you would need to update the `page-template.html` file by hand, as the instructions say.

So... I think it all works?  But please let me know, either way!

**Comment by greghendershott** [comment]
p.s. I'm trying this on Ubuntu. I imagine it would work on OS X, but I'm not sure. Also not sure about Windows.

**Comment by khinsen** [comment]
Works fine on OS X. And Frog works fine as well: with `uri-prefix = /~user/` and `output-dir = ~user`, I can run the Frog example site just fine. I'll try this on a more realistic site as soon as I can. Thanks a lot!

**Comment by greghendershott** [comment]
Cool. If it works for you on a realistic site, please let me know; I should update the README with a tip since it's non-obvious.

**Comment by greghendershott** [comment]
@khinsen I went ahead and updated the README with a tip, and, closed this issue.

If you experience any problems or confusion, please re-open and let me know.

**Comment by khinsen** [comment]
Quite on the contrary, this works fine. I added another level of convenience in #137, making is straightforward to create relocatable sites. For my application site, I now use `~user` as `uri-prefix` and `public_html` as `output-dir`, running Frog directly on the server.
