### ISSUE TITLE
frogrc option to use scrbl

### ISSUE THREAD

**Issue by lehitoskin** [greghendershott/frog#138]
There should be an option in the .frogrc file to have frog create a .scrbl instead of a .md when running `raco frog -n "new post title"`.

**Comment by greghendershott** [comment]
Thank you for making the suggestion.

Actually, using `-N` (capital `N`) creates a Scribble file.

```sh
$ raco frog -h
  ....snip....
* -n <title>, --new <title> : 
    Create a .md file for a new post based on today's date and <title>.
* -N <title>, --new-scribble <title> : 
    Create a .scrbl file for a new post based on today's date and <title>.
```

I'm guessing you just hadn't noticed this, and it will work fine for you. So I'm going to go ahead and close this. (However if I'm misunderstanding please feel free to re-open it.)

**Comment by lehitoskin** [comment]
Ah, I see. Thanks!
