### ISSUE TITLE
There should be a way to customize the "read more" link

### ISSUE THREAD

**Issue by lexi-lambda** [greghendershott/frog#140]
I'd like to change the "…more…" link to say something else. Currently, this is hardcoded into the HTML generation, but it would be nice to expose it as a config option or via template so it can be modified.

**Comment by greghendershott** [comment]
That's a good point.

It would easy enough to make this Yet Another .frogc Variable.  But I think instead it ought to be something you could customize in your `index-template.html` file. If I'd been smart enough to set it up like that in the first place, it would be straightforward. The example template would be something like:

```
<article>
  <header>
    <h2><a href='@|uri-path|'>@|title|</a></h2>
    <p class='date-and-tags'>@|date| :: @|tags|</p>
  </header>
  @|content|
  @(when more?
    @list{<footer class='read-more'>&hellip; more &hellip;>})
</article>
```

And you could tweak that. (But instead, there's no `@(when ....)` construct; the "more" HTML is currently hardwired into `@content`.)

So I need to mull over how to do this in some way that is backward-compatible but not too smelly.

**Comment by tfeb** [comment]
FWIW I agree with putting it into the template: avoiding a seething mass of what are essentially global variables in the config file is a win.

(I'm only saying this because I spend my working life dealing with people who think that software configured by 300 environment variables is a good design.)

**Comment by greghendershott** [comment]
My least-worst idea: Add two new template variables for `index-template.html`:

- `contents-only`: The post or blurb. Unlike `contents`, this never has any "..more.." link automatically appended.

- `more-uri`: When `contents-only` is a full post, this is `#f`. Else when `contents-only` is a blurb, this is the URI to the full post. In your `index-template.html` you can do something like:

  ```html
  @(when more-uri
    @list{<footer><a href='@|more-uri'>Read more&hellip;</a></footer>})
  ```

And I'll update the `example` project (which is also used by `raco frog --init`) to do that.

Existing blogs using `contents` will continue to work.

**Comment by greghendershott** [comment]
Actually there's an existing `uri-path` variable, so I think the second new variable should be a boolean `more?`. The template would look like this:

```html
<article>
  <header>
    <h2><a href='@|uri-path|'>@|title|</a></h2>
    <p class='date-and-tags'>@|date| :: @|tags|</p>
  </header>
  @|content-only|
  @(when more?
    @list{<footer>
            <a href='@|uri-path|'>&hellip; more &hellip;</a>
          </footer>})
</article>
```
