### ISSUE TITLE
Feature Request: Support for reStructuredText documents

### ISSUE THREAD

**Issue by ElijahCaine** [greghendershott/frog#153]
I write a lot of restructured text documents. I really like frog but was curious how difficult it'd be to add support to RST documents.

Is there a reason there isn't support for rst documents? I can grok that if that's the case.

I haven't ever written any racket but I'd be up for trying to implement it myself if I find the time and nobody else wants to do it.

**Comment by ElijahCaine** [comment]
Upon further inspection I realized there is no reStructuredText library for racket. That's a good enough reason to not have support for the format as far as I'm concerned.

**Comment by greghendershott** [comment]
In a similar vein, recently #148 asked for Org format support.

If someone wanted to write parsers for org and rst formats, provided they produce a list of x-expressions in the same style as the markdown parser, it would be fairly simple to wire them up in Frog.

Although it would be fun, I don't have time to do that myself. In fact I'm solely in maintenance mode for Frog itself, lately.
