### ISSUE TITLE
does Frog provide a canonical proc for converting title text to permalink stem?

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/frog#154]
E.g., `(f "Hello World! I'm Great")` becomes `"hello-world-im-great"`

**Comment by greghendershott** [comment]
Yes, [`our-encode`](https://github.com/greghendershott/frog/blob/13fbe6b079d340a3195d6a1afc70c2832ac7a7e5/frog/util.rkt#L46-L57). A better name might have been `slug`.
