### ISSUE TITLE
`xexpr->markdown` apparently doesn't convert hyperlinks — why not?

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/frog#155]
https://github.com/greghendershott/frog/blob/master/frog/xexpr2text.rkt#L45

Not in the sense of "why isn't this implemented" but rather "is there a reason one cannot easily convert hyperlinks".

**Comment by greghendershott** [comment]
In general you could easily convert an HTML/xexpr `a` element to a markdown `[label](uri)` link.  The contents of the `a` tag goes in the brackets, and the `herf` attribute in the parens.

If I remember correctly, that `xexpr->markdown` function is really intended as a helper for `xexpr->description`, which in turn is used to make "blurbs". So the fact that it is `provide`d is misleading, as is the name `xexpr->markdown`.

Having said that it would probably be better for a blurb to preserve the link.  Whether it used markdown syntax or simply the href.

**Comment by mbutterick** [comment]
Agreed
