### ISSUE TITLE
how to update `.frogrc`

### ISSUE THREAD

**Issue by mbutterick** [greghendershott/frog#158]
I find that when I update a `.frogrc` file, the changes are not always propagated throughout the project (e.g., changes to the structure of permalinks). The only thing that works is to delete the project and start over with `raco frog --init`. Is there some intermediate magic? I assume this is some kind of cache-invalidation problem. I've tried deleting the `.frog` directory, but that just makes frog loco.

**Comment by mbutterick** [comment]
OK, the intermediate magic that worked is manually deleting the `.frog/build` file before doing `raco frog -b`. I don't see this in the docs as a recommended technique so ... I’m hypothesizing that the `.frog/build` file ought to get invalidated when `.frogrc` changes.

**Comment by greg-at-droit** [comment]
There's a `-c` / `--clean` command-line flag to kill the cache.

The build cache was added relatively late in Frog's development, as opposed to being part of the design from the start. Also I've heard that cache invalidation is one of only two hard things about programming. :)

I'd be grateful to take a pull request to update the README. Or something more ambitious wrt to invalidating some/all of the build cache. Maybe automatically. Maybe after prompting/offering to do so. I think there are lots of reasonable choices here. Unfortunately I currently don't have time to think about them carefully and implement one.

**Comment by greghendershott** [comment]
There's a `-c` / `--clean` command-line flag to kill the cache.

The build cache was added relatively late in Frog's development, as opposed to being part of the design from the start. Also I've heard that cache invalidation is one of only two hard things about programming. :)

I'd be grateful to take a pull request to update the README. Or something more ambitious wrt to invalidating some/all of the build cache. Maybe automatically. Maybe after prompting/offering to do so. I think there are lots of reasonable choices here. Unfortunately I currently don't have time to think about them carefully and implement one.

**Comment by mbutterick** [comment]
Right on, thanks
