### ISSUE TITLE
Multiple authors?

### ISSUE THREAD

**Issue by bennn** [greghendershott/frog#162]
Can frog currently:
- list the author of a blog post on the post
- allow multiple authors (without changing the `.frogrc`)?

If not, I'm thinking I'll use tags like "by John Doe" as a hack. But it would be nice to start posts with:

```
  Title: ...
  Author: ...
  Date: ...
  Tags: ...
```

(My use case: I'd like to use frog for an "organizational" blog. Most posts will have different authors and I'd like to give each author credit.)

**Comment by gasche** [comment]
Indeed, I was just looking for the same feature this morning. It would be really nice to have.

**Comment by gasche** [comment]
So I started sending preliminary commits going in the direction of Author handling (but it's still work-in-progress) at #163, any feedback is welcome.

**Comment by gasche** [comment]
Thanks a lot!
