### ISSUE TITLE
Feeds generated by Frog do not display content on some clients (like Feedly)

### ISSUE THREAD

**Issue by k4rtik** [greghendershott/frog#168]
Both RSS and Atom feeds' `content` and `description` tags respectively should not include `<html>` tags in them. See lines https://github.com/greghendershott/frog/blob/master/frog/feeds.rkt#L78 and https://github.com/greghendershott/frog/blob/master/frog/feeds.rkt#L130.

I tried making the changes but couldn't test them locally failing to get `raco` to pick up my local changes. Gave up for lack of time, hence, this issue. I feel having some instructions in Contributing.md or README would be helpful for future contributions.

Thanks

**Comment by gasche** [comment]
Here is a proposed "use-case" for what kind of people would need instructions in Contributing.md or README, in case that can help to know what to write there:

> I know some Scheme/Lisp, I like the idea of using Frog, now
I want to hack a small thing / implement a feature, I just cloned
the github repository and then what?

> (In particular, while I probably used `raco pkg install frog`
to first try frog before deciding to do a modification, I did
that by reading Frog's install instructions and I may not be
familiar with the tool or packaging ecosystem.)

**Comment by tger** [comment]
I just contributed a major feature to Frog and I can add such a file documenting the workflow I have been using. Being new to Racket development I was also at a bit of a loss in the beginning so I can see the need for such a text.

**Comment by tger** [comment]
Here it is: https://github.com/greghendershott/frog/pull/170

**Comment by k4rtik** [comment]
Hi @greghendershott, can this issue be closed? I had provided a PR for this earlier: #169, would love to know if that needs more work.

Currently, this is how feeds generated using frog look in Feedly:

![screen shot 2016-12-17 at 17 54 32](https://cloud.githubusercontent.com/assets/374340/21290280/3bf4f58c-c482-11e6-88fc-6280153d4b51.png)

**Comment by greghendershott** [comment]
Fixed with merge of #169
