### ISSUE TITLE
Could .frogrc change the tag used for headings?

### ISSUE THREAD

**Issue by shriram** [greghendershott/frog#173]
I have in mind a use where the “heading” is not a header per se but much longer text — think an FAQ. The `h2` tag is pretty unsuitable for this. I'd like to be able to configure a different header tag (in fact, maybe no header at all — `em` would do just as well for an FAQ).

**Comment by tger** [comment]
Is this not a matter of editing `index-template.html`?

**Comment by tger** [comment]
Shiram, does the above work for you? If so I suggest closing this issue.
