### ISSUE TITLE
Inline verbatim text?

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [greghendershott/frog#182]
For me `@verbatim` creates a monospaced `display: block;` element. However, when I simply want to refer to a library or some element of coding in verbatim text in a paragraph, it breaks that paragraph.

Is there a better alternative? I would like to have something monospaced, meant for code, but inline and not block.

**Comment by greghendershott** [comment]
Maybe [`@tt`](https://docs.racket-lang.org/scribble/base.html#%28def._%28%28lib._scribble%2Fbase..rkt%29._tt%29%29) from `scribble/base`?

Also there are forms from `scribble/manual` for documenting code like `@racket` and `@tech`.

**Comment by ZelphirKaltstahl** [comment]
`tt` seems to work and I can change the style of it separately by changing the style for `.stt` in the `scribble.css`. Thanks!

It would be nicer, if there was a semantic function name for this kind of style, instead of "teletype", but it works : ) I am curious what the reasoning behind making `verbatim` produce a block element is. Is it thought of like: "There can be a whole block of verbatim text."? Because I think one could use a code block with unspecified syntax for that case.

For the other functions: `@tech` underlines the text, which is not bad, but makes it seem like it is a link and the name makes me think there is a definition for a "technical term" when I click it : ) `@racket` is less semantic than `@tt` in case of references to code things that are not racket, so i think `@tt` is my best bet for now.

**Comment by ZelphirKaltstahl** [comment]
I figured out something else:

If I simply use `@code`, it becomes a `span` element with class `.RktSym`. It is cleaner in the scribble source code for a blog post, even if the CSS class is weirdly named for non-Racket code. Initially `.RktSym` is not styled, so I added same styling I already had for `.stt` to `.RktSym` instead.

**Comment by greghendershott** [comment]
When I use Frog myself, I mostly write posts in markdown not scribble. It sounds like you've figured this out and understand it better than me, now, so I'm going to close this. :smile:
