### ISSUE TITLE
Using & in MathJax in Markdown incorrectly produces &amp;

### ISSUE THREAD

**Issue by wilbowma** [greghendershott/frog#183]
I'm guessing this is actually a bug in the Markdown parser.
Consider the following Markdown code:

```
\\[
\begin{array}{lrcl}                                                                                                                                                                                                
\text{Programs}&P \\
\end{array}
\\]
```

This incorrectly renders as `Programs    amp; P`, since `&` is converted to `&amp;` somewhere along the way.

**Comment by greghendershott** [comment]
I'll push a new `info.rkt` to bump the required version of the `markdown` package, as soon as the Racket package server has refreshed to have that new version. That should close this issue.
