### ISSUE TITLE
Move most of README into Scribble documentation

### ISSUE THREAD

**Issue by greghendershott** [greghendershott/frog#186]
Why:

- The README is very long.

- IIUC the Racket package server will, in the near future, show an "error" flag on packages with doc build errors (or that lack docs at all).

**Comment by lehitoskin** [comment]
I think I could help. What sections do you think should stay in the README?

**Comment by greghendershott** [comment]
Oh that's awesome and thank you so much for volunteering!

But I came here just now, to remove `help-wanted` and assign it to me, because I went ahead I'm a good 2/3 through writing the Scribble.

**Comment by lehitoskin** [comment]
lol, no worries.
