### ISSUE TITLE
Other repos currently using xexpr2text

### ISSUE THREAD

**Issue by LeifAndersen** [greghendershott/frog#195]
Other repos (namely http://github.com/racket/racket-lang-org ) are currently using your frog/xexpr2text module, which you have recently moved to the `private` folder.

Perhaps it will be worthwhile to either make a 'public' version of frog/xexpr2text, or split the functionality out into another module (like the xml package itself.) Just a thought anyway.

**Comment by greghendershott** [comment]
Ouch. Sorry. Until this recent change, where users' `frog.rkt` can `require` certain Frog modules, I considered Frog to be an application -- not a library. So I _thought_ I was being very responsible to sort out public vs. private, now. I didn't realize some people thought the whole thing was public, already. 😞 

ISTR `xexpr2txt` as some an ad hoc code that just (barely) does what Frog needs. Not something I'd offer as a great general solution for xexprs -> plain text. But let me take another look....  I'd also be totally cool if you wanted to copy-pasta...?  Or make a new Racket package for this that can grow in whatever ways people might want....?
