### ISSUE TITLE
Small error in section 5.4 Template example

### ISSUE THREAD

**Issue by ghoetker** [greghendershott/frog#197]
The example refers to code for the file "index-template.rkt".

Based on the rest of the page and what worked when I experimented, I think it should refer to "
"index-template.html". Note the changed file extension.

Frog rocks, by the way. Thanks.

**Comment by greghendershott** [comment]
Thanks for noticing and pointing that out! I'll push a fix soon.

**Comment by greghendershott** [comment]
Note: The Racket package server rebuilds documentation daily (usually early morning ET), so <http://docs.racket-lang.org/frog/index.html> might not reflect this for awhile.
