### ISSUE TITLE
Bad Date gives a Contract Error

### ISSUE THREAD

**Issue by maxsnew** [greghendershott/frog#199]
If you make a blog post with an invalid date like `2017-04-38T00:00:00` you get an unhelpful contract violation:

```
date: contract violation
  expected: (integer-in 1 31)
  given: 38
  context...:
   write-post-page
   /home/max/racket/share/racket/collects/racket/contract/private/arrow-higher-order.rkt:340:33
   /home/max/.racket/6.6/pkgs/frog/frog/frog.rkt:246:2: for-loop
   /home/max/.racket/6.6/pkgs/frog/frog/frog.rkt:173:0: build
   /home/max/racket/share/racket/collects/racket/cmdline.rkt:450:10: call-handler
   (submod /home/max/.racket/6.6/pkgs/frog/frog/frog.rkt main): [running body]
   /home/max/racket/share/racket/collects/raco/raco.rkt: [running body]
make: *** [Makefile:7: blog] Error 1
```

As a user this looked like an internal error in frog to me, because I expect contract errors to mean that internal invariants are broken (i.e., a bug).
A better error would be to report that there was an error in parsing/validating the blog post specifically naming the post that was problematic (the biggest problem with the above error).

I'd be happy to fix it myself, seems like you could either just catch this contract error and add the extra context that you were parsing the blog post, or better yet to make this a parse error and direct it to the line where it occurred.

**Comment by greghendershott** [comment]
Good point. Currently there's no input validation on the date, at all -- it's trusted to be valid ISO-8601 format string.

As a result, it's holding onto that string as-is, and blowing up only much later when trying to provide it as a `date` struct to the template.

If you wanted to contribute a fix, it would be probably be around [here](https://github.com/greghendershott/frog/blob/master/frog/private/posts.rkt#L133).  The result of the `hash-ref` should be validated and if it fails, report with `raise-user-error`.

Maybe replace:

```racket
           (hash-ref h "Date" (λ _ (err "missing `Date`")))
```

with something like:

```racket
           (with-handlers ([exn:fail?
                            (λ _ (raise-user-error
                                  'date
                                  "Date must be yyyy-mm-ddThr:mn:sc format."))])
             (date->date-struct (hash-ref h "Date" (λ _ (err "missing `Date`")))))
```

is my quick thought?  But welcome better ideas!

**Comment by greghendershott** [comment]
@maxsnew Were you still interested in contributing a fix, or, should I assign this to myself?
