### ISSUE TITLE
Code highlighting inside of a <details> tag?

### ISSUE THREAD

**Issue by hebr3** [greghendershott/frog#202]
I am trying to highlight code inside of a detail block. It seems to work fine in github markdown however, frog doesn't seem to do any conversion to the code inside of the details tag.

Do I need to write a custom widget function to do this, or is there a built in function already?

Code
---

`<details>`

` ```racket `
` (define (sqr x) `
`   (* x x)) `
` ``` `

`</details>`

Github markdown
---

<details>

```racket
(define (sqr x)
  (* x x))
```

</details>

frog markdown
---

 <details> <code>racket (define (sqr x) (* x x)) (define (cube x) (* x x x))</code></details>

**Comment by greghendershott** [comment]
Thanks for reporting. This is almost certainly due to the markdown parser used by frog. But I also wrote that, so I'm not dodging this. I logged [an issue there](https://github.com/greghendershott/markdown/issues/69).

**Comment by hebr3** [comment]
It would be helpful. As a work around I manually added the tags to the html file after frog did the conversion.

I'm not going to use it in every post so if it would be a hassle you can put it off until later.

**Comment by greghendershott** [comment]
It looks like the Racket package server has refreshed with this now, so you can [update Frog and its dependencies](http://docs.racket-lang.org/frog/Quick_start.html#%28part._.Updating_.Frog%29): `raco pkg update --update-deps frog`.  (The `--update-deps` will ensure that it fetches the newer `markdown` package, which is the substance of the change.)

**Comment by greghendershott** [comment]
p.s. That's weird, the GitHub UI is currently saying that I closed this issue, but not showing the link to the commit that closed it. For the record, it was commit fe408659f.
