### ISSUE TITLE
Pygments not working in Windows

### ISSUE THREAD

**Issue by passthejoe** [greghendershott/frog#208]
I just installed Racket, then Frog, then Python 3 and Pygments (via pip) in Windows 10, and my generated code snippets are not syntax-highlighted. 

Here is what the HTML looks like:

```
<div class="brush: racket">
 <pre><code>#lang web-server/insta

 ;; A "hello world" web server
 define (start request)
    (response/xexpr
        '(html
            (head (title "Racket"))
            (body "Hello World"))))</code></pre></div>
```

I think Pygments isn't working right. Python is in my Windows path, and I have checked on Pygments via the command line, but it doesn't seem to be working in Frog. I can see that I'm missing all the tags that color the text.

I'm assuming that Frog is having trouble starting Python. I tried to install Python as an adminstrator, and that didn't make any difference. If I remove Python entirely, the blog builds and looks the same -- I get the tagging above but none of the Pygments tagging for colors.

So does anybody have any tips on getting Racket/Frog to "talk" to Python in Windows 10?

**Comment by greghendershott** [comment]
I'm not sure, and don't have a Windows setup at-hand right now, but a few ideas:

- At a Racket prompt, what does `(find-executable-path "python")` return -- a path or `#f`?

- If `#f`: In your `frog.rkt`, in the call to [`syntax-highlight`](http://docs.racket-lang.org/frog/body-enhancers.html#%28def._%28%28lib._frog%2Fenhance-body..rkt%29._syntax-highlight%29%29) what if you change the `#:python-executable` value from `"python"` to `"c:\path\to\python"` -- does that help?

- Try running `raco frog --build --very-verbose` -- what if anything does that say about pygments?

**Comment by alex-hhh** [comment]
I am using frog on Windows 10 and syntax colorization is working fine.  I didn't do any special setup: I just installed python and pygments and  have the following entry in my frog.rkt:

```racket
(syntax-highlight #:python-executable "python.exe" #:line-numbers? #t #:css-class "source")
```

**Comment by passthejoe** [comment]
In the Racket shell, for `(find-executable-path "python")`, I do get `#f`.

For `#:python-executable`, I tried both of these, and neither worked:

`c:/Users/steve/AppData/Local/Programs/Python/Python36/python.exe` (I had to use forward slashes instead of backslashes to get `raco frog -bp` to work)
`python.exe`

The only output from `raco frog --build --very-verbose is:

`Frog 0.29`
`Very verbose mode`

**Comment by passthejoe** [comment]
I'm not exactly sure what did it, but I did get it to work! I did add Python to my local path and the system path.

Now I get this in a Racket shell:

```Welcome to Racket v6.12.
> (find-executable-path "python.exe")
#<path:C:\Users\steve\AppData\Local\Programs\Python\Python36\python.exe>
>
```

The syntax highlighting now works. Here is what I have in my `frog.rkt`:

```(~> xs
        (syntax-highlight #:python-executable "c:/Users/steve/AppData/Local/Programs/Python/Python36/python.exe"
                        #:line-numbers? #t
                        #:css-class "source")
        (auto-embed-tweets #:parents? #t)
        (add-racket-doc-links #:code? #t #:prose? #f)))
```

Thanks @greghendershott and @alex-hhh for your help.

**Comment by passthejoe** [comment]
I don't know if this "helped" or not, but in the windows shell, I navigated to the Python directory, ran the Racket shell from there, and then `(find-executable-path "python.exe") worked. Now it works in all directories. This could just be a *Racket in Windows* quirk.

**Comment by greghendershott** [comment]
Glad it's working!

1. Part of this sounds like ensuring Windows' PATH is set appropriately when racket/frog/pygments runs. I'm rusty on Windows and don't have any special advice for that; I'm not aware what Racket on Windows quirks there might be.

2. Above I kept saying `python` not `python.exe`. Sorry. That matters. In fact, Frog itself is defaulting `#:python-executable` to `"python"`, always. Instead, the default should vary and be `"python.exe"` when on Windows. If someone has time to make a PR, I'd happily take it. (Gist of it would be something like `(if (eq? (system-type) 'windows) "python.exe" "python")`.)

**Comment by passthejoe** [comment]
I think this is a Racket thing more than a Frog thing. I think the "secret sauce" is having the executable you are calling in your user's path in Windows. I tried `(find-executable-path "ruby.exe")` and got `#f`. I added the Ruby directory to my user path in Windows, and then I was able to find the path in Racket.
