### ISSUE TITLE
fresh post with blank Tag field signals one-time error

### ISSUE THREAD

**Issue by jbclements** [greghendershott/frog#211]
I just blew away my "build" file to rebuild my whole blog in order to get trailing slashes (cf #210 ), and I noticed a funny thing; all of the posts with an empty Tag field generated warnings such as this:

```
% raco frog -b
...
2012-03-28-different-ways-of-summing-string-lengths.md: Ignoring unknown metadata: "Tags:"
```

However, re-running frog made the errors go away, and the posts were built correctly.

Further investigation shows that this error is totally ignorable, and the post gets built fine. Since I was this deep already, I wrote a bit of code (and test case) to suppress the warning. I'll make a pull request.

**Comment by greghendershott** [comment]
I agree the warning is unnecessary.
