### ISSUE TITLE
RacketScript usage in documentation 

### ISSUE THREAD

**Issue by 11111000000** [greghendershott/frog#215]
Add racketscript to documentation (https://github.com/vishesh/racketscript)

**Comment by greghendershott** [comment]
I'm not sure what you have in mind. How would people use RacketScript in their Frog-generated blogs? What documentation would Frog need to provide?

**Comment by 11111000000** [comment]
Yes, Frog frontend must use RacketScript or urlang or something

**Comment by greghendershott** [comment]
Why?

**Comment by 11111000000** [comment]
it can't?

**Comment by LeifAndersen** [comment]
That's not an answer. 'Why do _you_ want RacketScript (oor urlang) for the front end?'

**Comment by 11111000000** [comment]
because of  s-expressions, macros,  tail call optimization, to share some scheme functions and data structures etc...

**Comment by greghendershott** [comment]
Unfortunately I still don't understand. So I can't do this myself. But I'll leave this open at least for awhile.

- If someone else understands, and submits a PR with the documentation change? I'd probably merge it.

- Or also: If someone submits a rough draft of the new text, right here on this issue? I can do some English prose editing and Scribble-izing. I just don't know how to write this from scratch.

**Comment by 11111000000** [comment]
yes, but in practice there is a lot of nuances, for example: hot-reloading, location of the shared resources, bundle injection, minification, etc. I can try myself and describe my experience, but if someone has already done it?

**Comment by greghendershott** [comment]
@11111000000 Yes, please. That would be great if you try, and describe your experience.

We can take it from there -- depending on your experience, talk about what to do next, and where.

Probably the `page-template.html` that Frog generates for your blog, is where you'd want to `<link>` your js file.  (I _think_ everything thereafter will be specific to RacketScript or Urlang, not Frog. But let's see.)

---

p.s. No, I don't know anyone who's doing. I'm not even sure why someone would -- for my own blog, I don't have any "fancy" "front-end" things I want to do. But that's just me. I'm not saying you're wrong to want to try this. Good luck!
