### ISSUE TITLE
Requiring in the template is cumbersome

### ISSUE THREAD

**Issue by sorawee** [greghendershott/frog#235]
Say, I want to call `(date->string date-struct)`. However, `date->string` is in `racket/date`, but we can't require it either because template rendering doesn't seem to allow `require`.

A way that I am currently using is:

```racket
@(define date->string (dynamic-require 'racket/date 'date->string))
```

which is obviously not ideal.

It would be nice to be able to supply user-custom variables for template rendering.

**Comment by greghendershott** [comment]
One of the items under "General Template Tips" in the docs is [this](https://docs.racket-lang.org/frog/templates.html#(part._.Use_local-require_in_templates)):

> 5.5.2 Use `local-require` in templates
>
> If you need to require a Racket module in your template, you must use `local-require`. Plain `require` won’t work because the template is not evaluated at a module level or top level.

Does that help?

**Comment by sorawee** [comment]
This addresses my issue. Thanks :)
